### ISSUE TITLE
FileNotFoundException: org/bridj/lib/win64/atiocl64.dll on Win64

### ISSUE THREAD

**Issue by ochafik** [ochafik/nativelibs4java#206]
What steps will reproduce the problem?
1. Run the HardwareReport JNLP

Java 7u1, 64-bit
Windows 7, 64-bit

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javaws.Launcher.executeApplication(Unknown Source)
	at com.sun.javaws.Launcher.executeMainClass(Unknown Source)
	at com.sun.javaws.Launcher.doLaunchApp(Unknown Source)
	at com.sun.javaws.Launcher.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ExceptionInInitializerError
	at com.nativelibs4java.opencl.demos.SetupUtils.failWithDownloadProposalsIfOpenCLNotAvailable(SetupUtils.java:34)
	at com.nativelibs4java.opencl.demos.hardware.HardwareReport.main(HardwareReport.java:223)
	... 9 more
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: org/bridj/lib/win64/atiocl64.dll
	at org.bridj.BridJ.findNativeLibraryFile(BridJ.java:782)
	at org.bridj.BridJ.getNativeLibraryFile(BridJ.java:679)
	at com.nativelibs4java.opencl.JavaCL.<clinit>(JavaCL.java:117)
	... 11 more
Caused by: java.io.FileNotFoundException: org/bridj/lib/win64/atiocl64.dll
	at org.bridj.Platform.extractEmbeddedLibraryResource(Platform.java:406)
	at org.bridj.BridJ.findNativeLibraryFile(BridJ.java:777)
	... 13 more

Issue was migrated from http://code.google.com/p/nativelibs4java/issues/detail?id=83
Original reporter : kap4020

**Comment by ochafik** [comment]
This issue was moved to ochafik/JavaCL#8
