### ISSUE TITLE
C++ Singleton pattern not working

### ISSUE THREAD

**Issue by slajar** [ochafik/nativelibs4java#291]
I have a class that is not beeing instanciated by new but by a public static member function.

class API_DECL Test
{
public:
	/** the contructor is not available to the public. You'll have to use the singleton patter getInstance() instead. */
	static Test * getInstance();
	
private:
	Test();
	static Test* instance;
};

Implementation looks like:

Test * Test::instance = NULL;

Test* Test::getInstance()
{
	if( Test::instance == NULL )
	{
		Test::instance = new Test();
	}
	return Test::instance;	
}

... 

Unfortunately, jnaerator doesn't generate bridj code to access this static getInstance function.

Ok, so I decided to work around this and generated a C-Function thats called "GetTestInstance()".

#ifdef __cplusplus
extern "C"
{
#endif

API_DECL Test* GetTestInstance();

#ifdef __cplusplus
} //extern "C"
#endif 

Internally I call Test::getInstance() to return Test pointer.
This compiles successfully. Unfortunately, that doesn't run well. It brings up a Memory error like this:

test = Pointer(peer = 0x5831b08, targetType = com.test.Test)
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:2367)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:587)
	at java.lang.StringBuilder.append(StringBuilder.java:214)
	at org.bridj.demangling.VC9Demangler.parseNameFragment(VC9Demangler.java:599)
	at org.bridj.demangling.VC9Demangler.parseNameQualification(VC9Demangler.java:642)
	at org.bridj.demangling.VC9Demangler.parseNameQualifications(VC9Demangler.java:627)
	at org.bridj.demangling.VC9Demangler.parseQualifiedTypeName(VC9Demangler.java:428)
	at org.bridj.demangling.VC9Demangler.parseType(VC9Demangler.java:364)
	at org.bridj.demangling.VC9Demangler.parseType(VC9Demangler.java:352)
	at org.bridj.demangling.VC9Demangler.parseFunctionProperty(VC9Demangler.java:117)
	at org.bridj.demangling.VC9Demangler.parseSymbol(VC9Demangler.java:215)
	at org.bridj.NativeLibrary.parseSymbol(NativeLibrary.java:359)
	at org.bridj.demangling.Demangler$Symbol.parse(Demangler.java:306)
	at org.bridj.demangling.Demangler$Symbol.matches(Demangler.java:284)
	at org.bridj.NativeLibrary.getSymbol(NativeLibrary.java:195)
	at org.bridj.cpp.CPPRuntime.registerNativeMethod(CPPRuntime.java:263)
	at org.bridj.CRuntime.register(CRuntime.java:357)
	at org.bridj.CRuntime.register(CRuntime.java:266)
	at org.bridj.CRuntime$CTypeInfo.<init>(CRuntime.java:83)
	at org.bridj.cpp.CPPRuntime$CPPTypeInfo.<init>(CPPRuntime.java:704)
	at org.bridj.cpp.CPPRuntime.getTypeInfo(CPPRuntime.java:804)
	at org.bridj.BridJ.getTypeInfo(BridJ.java:309)
	at org.bridj.BridJ.createNativeObjectFromPointer(BridJ.java:206)
	at org.bridj.BridJ.createNativeObjectFromPointer(BridJ.java:222)
	at org.bridj.Pointer.getNativeObjectAtOffset(Pointer.java:690)
	at org.bridj.CommonPointerIOs$NativeObjectPointerIO.get(CommonPointerIOs.java:43)
	at org.bridj.CommonPointerIOs$NativeObjectPointerIO.get(CommonPointerIOs.java:11)
	at org.bridj.Pointer.get(Pointer.java:831)
	at org.bridj.Pointer.get(Pointer.java:800)

How can I solve this issue in a good way that is compliant with Bridj and JNAerator? I can still change the C++ Api to fit any needs.

**Comment by ochafik** [comment]
This issue was moved to ochafik/BridJ#16

**Comment by MarvelFisher** [comment]
Hi @slajar 
I meet same problem when using VS compiler. This is caused by VS demangling dll.
My solution is by modify source code of Bridj:
Package: org.bridj.demangling
Class: VC9Demangler
Method: private List parseParams() throws DemanglingException {
    List<TypeRef> paramTypes = new ArrayList<TypeRef>();
    if (!consumeCharIf('X')) {          
        char c;            
        // add 3 line here
        if (peekChar() == '@') {
            consumeChar();
        }
        while ((c = peekChar() ) != '@' && c != 0 && (c != 'Z' || peekChar(2) == 'Z')) {

            TypeRef tr = parseType(false);
            if (tr == null) {
                continue;
            }
            paramTypes.add(tr);
        }
        if (c == 'Z') {
            consumeChar();
        }
        //break;
        if (c == '@') {
            consumeChar();
        }
    }
    return paramTypes;
}
and build again.
Hope this can help you.
