### ISSUE TITLE
ScalaCL: ScalaCLFunctionsTransform exception when running sample code on website

### ISSUE THREAD

**Issue by dbarowy** [ochafik/nativelibs4java#310]
I get this error when compiling the sample code with 'scalac Test.scala'.  Running this in the scala REPL reveals that calling 'map(p => p._1 * p._2)' on 'scalacl.CLIndexedSeq'.

Am I missing something here or is this a bug?  I am not familiar enough with scalac passes to diagnose myself.

colTpe = scalacl.CLIndexedSeq[(Int, Int)]
colTpe.typeSymbol.typeConstructor = scalacl.CLIndexedSeq
colTpe.typeSymbol.typeConstructor == CLArray = false
OpenCL colTpe ; op = map
ScalaCLFunctionsTransform: Exception getting CLDataIO for tuple.  e=scala.Predef$.assert(Predef.scala:89)
scalacl.impl.CLTupleDataIO.<init>(CLDataIO.scala:120)
scalacl.plugin.ScalaCLFunctionsTransformComponent.getDataIOByTupleInfo(ScalaCLFunctionsTransformComponent.scala:92)
scalacl.plugin.ScalaCLFunctionsTransformComponent$$anonfun$getDataIOByTupleInfo$1.apply(ScalaCLFunctionsTransformComponent.scala:92)
scalacl.plugin.ScalaCLFunctionsTransformComponent$$anonfun$getDataIOByTupleInfo$1.apply(ScalaCLFunctionsTransformComponent.scala:92)
scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:194)
scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:194)
scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:34)
scala.collection.mutable.ArrayOps.foreach(ArrayOps.scala:38)
scala.collection.TraversableLike$class.map(TraversableLike.scala:194)
scala.collection.mutable.ArrayOps.map(ArrayOps.scala:38)
scalacl.plugin.ScalaCLFunctionsTransformComponent.getDataIOByTupleInfo(ScalaCLFunctionsTransformComponent.scala:92)
scalacl.plugin.ScalaCLFunctionsTransformComponent.getDataIO(ScalaCLFunctionsTransformComponent.scala:108)
scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1.scalacl$plugin$ScalaCLFunctionsTransformComponent$$anon$$getDataIOImplicit(ScalaCLFunctionsTransformComponent.scala:215)
scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1$$anonfun$20.apply(ScalaCLFunctionsTransformComponent.scala:397)
scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1$$anonfun$20.apply(ScalaCLFunctionsTransformComponent.scala:397)
scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:194)
scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:194)
scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:34)
scala.collection.mutable.ArrayOps.foreach(ArrayOps.scala:38)
scala.collection.TraversableLike$class.map(TraversableLike.scala:194)
scala.collection.mutable.ArrayOps.map(ArrayOps.scala:38)
scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1.scalacl$plugin$ScalaCLFunctionsTransformComponent$$anon$$convertFunctionToCLFunction(ScalaCLFunctionsTransformComponent.scala:397)
scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1$$anonfun$transform$2.apply(ScalaCLFunctionsTransformComponent.scala:542)
scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1$$anonfun$transform$2.apply(ScalaCLFunctionsTransformComponent.scala:541)
com.nativelibs4java.scalaxy.common.TreeBuilders$class.msg(TreeBuilders.scala:62)
scalacl.plugin.ScalaCLFunctionsTransformComponent.msg(ScalaCLFunctionsTransformComponent.scala:59)
scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1.transform(ScalaCLFunctionsTransformComponent.scala:541)
scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:845)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:53)
scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1.transform(ScalaCLFunctionsTransformComponent.scala:574)
scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:835)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:53)
scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1.transform(ScalaCLFunctionsTransformComponent.scala:574)
scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:837)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:53)
scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1.transform(ScalaCLFunctionsTransformComponent.scala:574)
scala.tools.nsc.ast.Trees$Transformer$$anonfun$transform$4.apply(Trees.scala:777)
scala.tools.nsc.ast.Trees$Transformer$$anonfun$transform$4.apply(Trees.scala:776)
scala.tools.nsc.ast.Trees$Transformer.atOwner(Trees.scala:899)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:31)
scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:775)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:53)
scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1.transform(ScalaCLFunctionsTransformComponent.scala:574)
scala.tools.nsc.ast.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:891)
scala.tools.nsc.ast.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:889)
scala.collection.immutable.List.loop$1(List.scala:117)
scala.collection.immutable.List.mapConserve(List.scala:133)
scala.tools.nsc.ast.Trees$Transformer.transformStats(Trees.scala:889)
scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:799)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:53)
scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1.transform(ScalaCLFunctionsTransformComponent.scala:574)
scala.tools.nsc.ast.Trees$Transformer$$anonfun$transform$5.apply(Trees.scala:783)
scala.tools.nsc.ast.Trees$Transformer$$anonfun$transform$5.apply(Trees.scala:781)
scala.tools.nsc.ast.Trees$Transformer.atOwner(Trees.scala:899)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:31)
scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:780)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:53)
scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1.transform(ScalaCLFunctionsTransformComponent.scala:574)
scala.tools.nsc.ast.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:891)
scala.tools.nsc.ast.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:889)
scala.collection.immutable.List.loop$1(List.scala:117)
scala.collection.immutable.List.mapConserve(List.scala:133)
scala.tools.nsc.ast.Trees$Transformer.transformStats(Trees.scala:889)
scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:797)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.scala$tools$nsc$transform$TypingTransformers$TypingTransformer$$super$transform(TypingTransformers.scala:49)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$1.apply(TypingTransformers.scala:49)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$1.apply(TypingTransformers.scala:49)
scala.tools.nsc.ast.Trees$Transformer.atOwner(Trees.scala:899)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:31)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:49)
scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1.transform(ScalaCLFunctionsTransformComponent.scala:574)
scala.tools.nsc.ast.Trees$Transformer.transformTemplate(Trees.scala:875)
scala.tools.nsc.ast.Trees$Transformer$$anonfun$transform$3.apply(Trees.scala:772)
scala.tools.nsc.ast.Trees$Transformer$$anonfun$transform$3.apply(Trees.scala:771)
scala.tools.nsc.ast.Trees$Transformer.atOwner(Trees.scala:899)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:31)
scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:770)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:53)
scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1.transform(ScalaCLFunctionsTransformComponent.scala:574)
scala.tools.nsc.ast.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:891)
scala.tools.nsc.ast.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:889)
scala.collection.immutable.List.loop$1(List.scala:117)
scala.collection.immutable.List.mapConserve(List.scala:133)
scala.tools.nsc.ast.Trees$Transformer.transformStats(Trees.scala:889)
scala.tools.nsc.ast.Trees$Transformer$$anonfun$transform$1.apply(Trees.scala:761)
scala.tools.nsc.ast.Trees$Transformer$$anonfun$transform$1.apply(Trees.scala:761)
scala.tools.nsc.ast.Trees$Transformer.atOwner(Trees.scala:899)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:31)
scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:760)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.scala$tools$nsc$transform$TypingTransformers$TypingTransformer$$super$transform(TypingTransformers.scala:49)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$2.apply(TypingTransformers.scala:51)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$2.apply(TypingTransformers.scala:51)
scala.tools.nsc.ast.Trees$Transformer.atOwner(Trees.scala:899)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:31)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:51)
scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1.transform(ScalaCLFunctionsTransformComponent.scala:574)
scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:892)
scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:329)
scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:297)
scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:297)
scala.collection.Iterator$class.foreach(Iterator.scala:660)
scala.collection.mutable.ListBuffer$$anon$1.foreach(ListBuffer.scala:316)
scala.tools.nsc.Global$GlobalPhase.run(Global.scala:297)
scala.tools.nsc.Global$Run.compileSources(Global.scala:953)
scala.tools.nsc.Global$Run.compile(Global.scala:1038)
scala.tools.nsc.Main$.process(Main.scala:106)
scala.tools.nsc.Main$.main(Main.scala:123)
scala.tools.nsc.Main.main(Main.scala)

warning: [scalacl] Test.scala:9 An unexpected error occurred while attempting an optimization
[scalacl] Test.scala:9   Attempted optimization : 'associated equivalent OpenCL source to scalacl.CLIndexedSeq[(Int, Int)].map's function argument.'
[scalacl] Test.scala:9   You can skip this line with the following environment variable :
[scalacl] Test.scala:9     SCALACL_SKIP=Test.scala:9
[scalacl] Test.scala:9   To display the error and help debug the ScalaCL compiler plugin, please set the following environment variable :
[scalacl] Test.scala:9     SCALACL_TRACE=1
[scalacl] Test.scala:9   You can help by filing bugs here (with [ScalaCLPlugin] in the title) :
[scalacl] Test.scala:9     http://code.google.com/p/nativelibs4java/issues/entry
[scalacl] Test.scala:9 An unexpected error occurred while attempting an optimization
[scalacl] Test.scala:9   Attempted optimization : 'associated equivalent OpenCL source to scalacl.CLIndexedSeq[(Int, Int)].map's function argument.'
[scalacl] Test.scala:9   You can skip this line with the following environment variable :
[scalacl] Test.scala:9     SCALACL_SKIP=Test.scala:9
[scalacl] Test.scala:9   To display the error and help debug the ScalaCL compiler plugin, please set the following environment variable :
[scalacl] Test.scala:9     SCALACL_TRACE=1
[scalacl] Test.scala:9   You can help by filing bugs here (with [ScalaCLPlugin] in the title) :
[scalacl] Test.scala:9     http://code.google.com/p/nativelibs4java/issues/entry
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:89)
	at scalacl.impl.CLTupleDataIO.<init>(CLDataIO.scala:120)
	at scalacl.plugin.ScalaCLFunctionsTransformComponent.getDataIOByTupleInfo(ScalaCLFunctionsTransformComponent.scala:92)
	at scalacl.plugin.ScalaCLFunctionsTransformComponent$$anonfun$getDataIOByTupleInfo$1.apply(ScalaCLFunctionsTransformComponent.scala:92)
	at scalacl.plugin.ScalaCLFunctionsTransformComponent$$anonfun$getDataIOByTupleInfo$1.apply(ScalaCLFunctionsTransformComponent.scala:92)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:194)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:194)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:34)
	at scala.collection.mutable.ArrayOps.foreach(ArrayOps.scala:38)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:194)
	at scala.collection.mutable.ArrayOps.map(ArrayOps.scala:38)
	at scalacl.plugin.ScalaCLFunctionsTransformComponent.getDataIOByTupleInfo(ScalaCLFunctionsTransformComponent.scala:92)
	at scalacl.plugin.ScalaCLFunctionsTransformComponent.getDataIO(ScalaCLFunctionsTransformComponent.scala:108)
	at scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1.scalacl$plugin$ScalaCLFunctionsTransformComponent$$anon$$getDataIOImplicit(ScalaCLFunctionsTransformComponent.scala:215)
	at scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1$$anonfun$20.apply(ScalaCLFunctionsTransformComponent.scala:397)
	at scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1$$anonfun$20.apply(ScalaCLFunctionsTransformComponent.scala:397)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:194)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:194)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:34)
	at scala.collection.mutable.ArrayOps.foreach(ArrayOps.scala:38)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:194)
	at scala.collection.mutable.ArrayOps.map(ArrayOps.scala:38)
	at scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1.scalacl$plugin$ScalaCLFunctionsTransformComponent$$anon$$convertFunctionToCLFunction(ScalaCLFunctionsTransformComponent.scala:397)
	at scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1$$anonfun$transform$2.apply(ScalaCLFunctionsTransformComponent.scala:542)
	at scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1$$anonfun$transform$2.apply(ScalaCLFunctionsTransformComponent.scala:541)
	at com.nativelibs4java.scalaxy.common.TreeBuilders$class.msg(TreeBuilders.scala:62)
	at scalacl.plugin.ScalaCLFunctionsTransformComponent.msg(ScalaCLFunctionsTransformComponent.scala:59)
	at scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1.transform(ScalaCLFunctionsTransformComponent.scala:541)
	at scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:845)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:53)
	at scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1.transform(ScalaCLFunctionsTransformComponent.scala:574)
	at scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:835)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:53)
	at scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1.transform(ScalaCLFunctionsTransformComponent.scala:574)
	at scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:837)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:53)
	at scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1.transform(ScalaCLFunctionsTransformComponent.scala:574)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transform$4.apply(Trees.scala:777)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transform$4.apply(Trees.scala:776)
	at scala.tools.nsc.ast.Trees$Transformer.atOwner(Trees.scala:899)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:31)
	at scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:775)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:53)
	at scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1.transform(ScalaCLFunctionsTransformComponent.scala:574)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:891)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:889)
	at scala.collection.immutable.List.loop$1(List.scala:117)
	at scala.collection.immutable.List.mapConserve(List.scala:133)
	at scala.tools.nsc.ast.Trees$Transformer.transformStats(Trees.scala:889)
	at scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:799)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:53)
	at scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1.transform(ScalaCLFunctionsTransformComponent.scala:574)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transform$5.apply(Trees.scala:783)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transform$5.apply(Trees.scala:781)
	at scala.tools.nsc.ast.Trees$Transformer.atOwner(Trees.scala:899)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:31)
	at scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:780)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:53)
	at scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1.transform(ScalaCLFunctionsTransformComponent.scala:574)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:891)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:889)
	at scala.collection.immutable.List.loop$1(List.scala:117)
	at scala.collection.immutable.List.mapConserve(List.scala:133)
	at scala.tools.nsc.ast.Trees$Transformer.transformStats(Trees.scala:889)
	at scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:797)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.scala$tools$nsc$transform$TypingTransformers$TypingTransformer$$super$transform(TypingTransformers.scala:49)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$1.apply(TypingTransformers.scala:49)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$1.apply(TypingTransformers.scala:49)
	at scala.tools.nsc.ast.Trees$Transformer.atOwner(Trees.scala:899)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:31)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:49)
	at scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1.transform(ScalaCLFunctionsTransformComponent.scala:574)
	at scala.tools.nsc.ast.Trees$Transformer.transformTemplate(Trees.scala:875)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transform$3.apply(Trees.scala:772)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transform$3.apply(Trees.scala:771)
	at scala.tools.nsc.ast.Trees$Transformer.atOwner(Trees.scala:899)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:31)
	at scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:770)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:53)
	at scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1.transform(ScalaCLFunctionsTransformComponent.scala:574)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:891)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:889)
	at scala.collection.immutable.List.loop$1(List.scala:117)
	at scala.collection.immutable.List.mapConserve(List.scala:133)
	at scala.tools.nsc.ast.Trees$Transformer.transformStats(Trees.scala:889)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transform$1.apply(Trees.scala:761)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transform$1.apply(Trees.scala:761)
	at scala.tools.nsc.ast.Trees$Transformer.atOwner(Trees.scala:899)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:31)
	at scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:760)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.scala$tools$nsc$transform$TypingTransformers$TypingTransformer$$super$transform(TypingTransformers.scala:49)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$2.apply(TypingTransformers.scala:51)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$2.apply(TypingTransformers.scala:51)
	at scala.tools.nsc.ast.Trees$Transformer.atOwner(Trees.scala:899)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:31)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:51)
	at scalacl.plugin.ScalaCLFunctionsTransformComponent$$anon$1.transform(ScalaCLFunctionsTransformComponent.scala:574)
	at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:892)
	at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:329)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:297)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:297)
	at scala.collection.Iterator$class.foreach(Iterator.scala:660)
	at scala.collection.mutable.ListBuffer$$anon$1.foreach(ListBuffer.scala:316)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:297)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:953)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1038)
	at scala.tools.nsc.Main$.process(Main.scala:106)
	at scala.tools.nsc.Main$.main(Main.scala:123)
	at scala.tools.nsc.Main.main(Main.scala)
colTpe = scalacl.CLRange
colTpe.typeSymbol.typeConstructor = scalacl.CLRange
colTpe.typeSymbol.typeConstructor == CLArray = false
OpenCL colTpe ; op = map
one warning found

**Comment by ochafik** [comment]
This issue was moved to ochafik/ScalaCL#18
