### ISSUE TITLE
bound check/GetLastError()

### ISSUE THREAD

**Issue by smori-tib** [ochafik/nativelibs4java#361]
I am getting a runtime error when using the jnaerator generated code with BridJ binding from Windows headers. This the snippet from the headers:

#define ANYSIZE_ARRAY 1

typedef struct _SID_AND_ATTRIBUTES {
    PSID Sid;
    DWORD Attributes;
} SID_AND_ATTRIBUTES, * PSID_AND_ATTRIBUTES;

typedef struct _TOKEN_GROUPS {
    DWORD GroupCount;
    SID_AND_ATTRIBUTES Groups[ANYSIZE_ARRAY];
} TOKEN_GROUPS, *PTOKEN_GROUPS;

I am allocating the exact number of bytes required by GetTokenInformation() to populate TOKEN_GROUPS. For the purpose of what I am doing, GetTokenInformation populates more than 1 element in TOKEN_GROUPS.Groups attribute. The actual number of elements in Groups is defined by GroupCount and that can only be determined at runtime.
I get this exception when accessing Sid() from TOKEN_GROUPS.Groups[1]:
Exception in thread "main" java.lang.IndexOutOfBoundsException: Cannot access to memory data of length 8 at offset 0 : valid memory start is 229081408, valid memory size is 24
        at org.bridj.Pointer.checkPeer(Pointer.java:1094)
        at org.bridj.Pointer$OrderedPointer.getLongAtOffset(Pointer.java:300)
        at org.bridj.Pointer.getSizeTAtOffset(Pointer.java:3996)
        at org.bridj.Pointer.getPointerAtOffset(Pointer.java:3688)
        at org.bridj.Pointer.getPointerAtOffset(Pointer.java:3680)
        at org.bridj.StructIO.getPointerField(StructIO.java:898)
        at test.advapi32.SID_AND_ATTRIBUTES.Sid(SID_AND_ATTRIBUTES.java:20)
...
sizeof(SID_AND_ATTRIBUTES) reports 8 in standalone win32 application.

If I use an arbitrarily large number for ANYSIZE_ARRAY, say 100, I get this exception when accessing TOKEN_GROUPS.Groups():
Exception in thread "main" java.lang.IndexOutOfBoundsException: Cannot extend validity of pointed memory from 234914436 to 234915720
        at org.bridj.Pointer.validBytes(Pointer.java:1140)
        at org.bridj.Pointer.validElements(Pointer.java:1180)
        at org.bridj.StructIO.getPointerField(StructIO.java:896)
        at test.advapi32.TOKEN_GROUPS.Groups(TOKEN_GROUPS.java:31)
...

Things work fine when I set ANYARRAY_SIZE to match the exact number of groups.

Any suggestion how to solve this?

Another thing that I observed. I generated GetLastError() also but it seems that the error code are getting swallowed. It always returns 0 even when an error occurred. However, exception is thrown if I add throws LastError in the method signature. Is it possible to get the error code through GetLastError() as opposed to from exception?

**Comment by ochafik** [comment]
This issue was moved to ochafik/BridJ#25
