### ISSUE TITLE
[ScalaCLPlugin] 'cannot find class manifest for element type T' during optimization of Array[Int].map with Manifest

### ISSUE THREAD

**Issue by ochafik** [ochafik/nativelibs4java#47]
<b>What steps will reproduce the problem?</b>

% SCALACL_VERBOSE=1 SCALACL_TRACE=1 scala
scala> def f[T: Manifest](p: Int => T): Array[T] = Array(1, 2).map(x => p(x + 1)).toArray

What is the expected output?

f: [T](p: (Int) => T)(implicit evidence$1: Manifest[T])Array[T]

What do you see instead?

scala.tools.nsc.symtab.Types$TypeError: cannot find class manifest for element type T
	at scala.tools.nsc.typechecker.Contexts$Context.error(Contexts.scala:274)
	at scala.tools.nsc.typechecker.Infer$Inferencer.error(Infer.scala:205)
	at scala.tools.nsc.typechecker.Typers$Typer.getManifestTree(Typers.scala:4361)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:4061)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:4203)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:4252)
	at scalacl.TreeBuilders$class.newArrayWithArrayType(TreeBuilders.scala:200)
	at scalacl.LoopsTransformComponent.newArrayWithArrayType(LoopsTransformComponent.scala:60)
	at scalacl.TreeBuilders$class.newArray(TreeBuilders.scala:197)
	at scalacl.LoopsTransformComponent.newArray(LoopsTransformComponent.scala:60)
	at scalacl.RewritingPluginComponent$CollectionRewriters$ArrayRewriter$.newBuilder(CollectionRewriters.scala:540)
	at scalacl.LoopsTransformComponent$$anon$1$$anonfun$transform$4$$anonfun$apply$30.apply(LoopsTransformComponent.scala:715)
	at scalacl.LoopsTransformComponent$$anon$1$$anonfun$transform$4$$anonfun$apply$30.apply(LoopsTransformComponent.scala:714)
	at scalacl.RewritingPluginComponent$CollectionRewriters$ArrayRewriter$.foreach(CollectionRewriters.scala:586)
	at scalacl.LoopsTransformComponent$$anon$1$$anonfun$transform$4.apply(LoopsTransformComponent.scala:708)
	at scalacl.LoopsTransformComponent$$anon$1$$anonfun$transform$4.apply(LoopsTransformComponent.scala:249)
	at scalacl.TreeBuilders$class.msg(TreeBuilders.scala:61)
	at scalacl.LoopsTransformComponent.msg(LoopsTransformComponent.scala:60)
	at scalacl.LoopsTransformComponent$$anon$1.transform(LoopsTransformComponent.scala:248)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:851)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:851)
	at scala.collection.immutable.List.loop$1(List.scala:115)
	at scala.collection.immutable.List.mapConserve(List.scala:132)
	at scala.tools.nsc.ast.Trees$Transformer.transformTrees(Trees.scala:851)
	at scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:815)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:53)
	at scalacl.LoopsTransformComponent$$anon$1.transform(LoopsTransformComponent.scala:763)
	at scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:823)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:53)
	at scalacl.LoopsTransformComponent$$anon$1.transform(LoopsTransformComponent.scala:763)
	at scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:813)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:53)
	at scalacl.LoopsTransformComponent$$anon$1.transform(LoopsTransformComponent.scala:763)
	at scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:815)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:53)
	at scalacl.LoopsTransformComponent$$anon$1.transform(LoopsTransformComponent.scala:758)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transform$5.apply(Trees.scala:761)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transform$5.apply(Trees.scala:759)
	at scala.tools.nsc.ast.Trees$Transformer.atOwner(Trees.scala:877)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:31)
	at scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:758)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:53)
	at scalacl.LoopsTransformComponent$$anon$1.transform(LoopsTransformComponent.scala:763)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:869)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:867)
	at scala.collection.immutable.List.loop$1(List.scala:115)
	at scala.collection.immutable.List.mapConserve(List.scala:132)
	at scala.tools.nsc.ast.Trees$Transformer.transformStats(Trees.scala:867)
	at scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:775)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.scala$tools$nsc$transform$TypingTransformers$TypingTransformer$$super$transform(TypingTransformers.scala:49)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$1.apply(TypingTransformers.scala:49)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$1.apply(TypingTransformers.scala:49)
	at scala.tools.nsc.ast.Trees$Transformer.atOwner(Trees.scala:877)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:31)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:49)
	at scalacl.LoopsTransformComponent$$anon$1.transform(LoopsTransformComponent.scala:763)
	at scala.tools.nsc.ast.Trees$Transformer.transformTemplate(Trees.scala:853)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transform$3.apply(Trees.scala:750)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transform$3.apply(Trees.scala:749)
	at scala.tools.nsc.ast.Trees$Transformer.atOwner(Trees.scala:877)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:31)
	at scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:748)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:53)
	at scalacl.LoopsTransformComponent$$anon$1.transform(LoopsTransformComponent.scala:763)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:869)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:867)
	at scala.collection.immutable.List.loop$1(List.scala:115)
	at scala.collection.immutable.List.mapConserve(List.scala:132)
	at scala.tools.nsc.ast.Trees$Transformer.transformStats(Trees.scala:867)
	at scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:775)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.scala$tools$nsc$transform$TypingTransformers$TypingTransformer$$super$transform(TypingTransformers.scala:49)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$1.apply(TypingTransformers.scala:49)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$1.apply(TypingTransformers.scala:49)
	at scala.tools.nsc.ast.Trees$Transformer.atOwner(Trees.scala:877)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:31)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:49)
	at scalacl.LoopsTransformComponent$$anon$1.transform(LoopsTransformComponent.scala:763)
	at scala.tools.nsc.ast.Trees$Transformer.transformTemplate(Trees.scala:853)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transform$3.apply(Trees.scala:750)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transform$3.apply(Trees.scala:749)
	at scala.tools.nsc.ast.Trees$Transformer.atOwner(Trees.scala:877)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:31)
	at scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:748)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:53)
	at scalacl.LoopsTransformComponent$$anon$1.transform(LoopsTransformComponent.scala:763)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:869)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:867)
	at scala.collection.immutable.List.loop$1(List.scala:115)
	at scala.collection.immutable.List.mapConserve(List.scala:132)
	at scala.tools.nsc.ast.Trees$Transformer.transformStats(Trees.scala:867)
	at scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:775)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.scala$tools$nsc$transform$TypingTransformers$TypingTransformer$$super$transform(TypingTransformers.scala:49)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$1.apply(TypingTransformers.scala:49)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$1.apply(TypingTransformers.scala:49)
	at scala.tools.nsc.ast.Trees$Transformer.atOwner(Trees.scala:877)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:31)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:49)
	at scalacl.LoopsTransformComponent$$anon$1.transform(LoopsTransformComponent.scala:763)
	at scala.tools.nsc.ast.Trees$Transformer.transformTemplate(Trees.scala:853)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transform$3.apply(Trees.scala:750)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transform$3.apply(Trees.scala:749)
	at scala.tools.nsc.ast.Trees$Transformer.atOwner(Trees.scala:877)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:31)
	at scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:748)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:53)
	at scalacl.LoopsTransformComponent$$anon$1.transform(LoopsTransformComponent.scala:763)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:869)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:867)
	at scala.collection.immutable.List.loop$1(List.scala:115)
	at scala.collection.immutable.List.mapConserve(List.scala:132)
	at scala.tools.nsc.ast.Trees$Transformer.transformStats(Trees.scala:867)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transform$1.apply(Trees.scala:739)
	at scala.tools.nsc.ast.Trees$Transformer$$anonfun$transform$1.apply(Trees.scala:739)
	at scala.tools.nsc.ast.Trees$Transformer.atOwner(Trees.scala:877)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:31)
	at scala.tools.nsc.ast.Trees$Transformer.transform(Trees.scala:738)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.scala$tools$nsc$transform$TypingTransformers$TypingTransformer$$super$transform(TypingTransformers.scala:49)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$2.apply(TypingTransformers.scala:51)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$2.apply(TypingTransformers.scala:51)
	at scala.tools.nsc.ast.Trees$Transformer.atOwner(Trees.scala:877)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:31)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:51)
	at scalacl.LoopsTransformComponent$$anon$1.transform(LoopsTransformComponent.scala:763)
	at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:870)
	at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply(Global.scala:282)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply(Global.scala:282)
	at scala.tools.nsc.reporters.Reporter.withSource(Reporter.scala:48)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:282)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:256)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:256)
	at scala.collection.Iterator$class.foreach(Iterator.scala:631)
	at scala.collection.mutable.ListBuffer$$anon$1.foreach(ListBuffer.scala:304)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:256)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:741)
	at scala.tools.nsc.Interpreter.compileAndSaveRun(Interpreter.scala:518)
	at scala.tools.nsc.Interpreter$Request.objRun(Interpreter.scala:892)
	at scala.tools.nsc.Interpreter$Request.compile(Interpreter.scala:915)
	at scala.tools.nsc.Interpreter.interpret(Interpreter.scala:598)
	at scala.tools.nsc.Interpreter.interpret(Interpreter.scala:577)
	at scala.tools.nsc.InterpreterLoop.reallyInterpret$1(InterpreterLoop.scala:472)
	at scala.tools.nsc.InterpreterLoop.interpretStartingWith(InterpreterLoop.scala:515)
	at scala.tools.nsc.InterpreterLoop.command(InterpreterLoop.scala:362)
	at scala.tools.nsc.InterpreterLoop.processLine$1(InterpreterLoop.scala:243)
	at scala.tools.nsc.InterpreterLoop.repl(InterpreterLoop.scala:249)
	at scala.tools.nsc.InterpreterLoop.main(InterpreterLoop.scala:559)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:72)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
warning: [scalacl] <console>:5 An unexpected error occurred while attempting an optimization
[scalacl] <console>:5   Attempted optimization : 'transformed Array[Int].map into equivalent while loop.'
[scalacl] <console>:5   You can skip this line with the following environment variable :
[scalacl] <console>:5     SCALACL_SKIP=<console>:5
[scalacl] <console>:5 	Error : scala.tools.nsc.symtab.Types$TypeError: cannot find class manifest for element type T
[scalacl] <console>:5 An unexpected error occurred while attempting an optimization
[scalacl] <console>:5   Attempted optimization : 'transformed Array[Int].map into equivalent while loop.'
[scalacl] <console>:5   You can skip this line with the following environment variable :
[scalacl] <console>:5     SCALACL_SKIP=<console>:5
[scalacl] <console>:5 	Error : scala.tools.nsc.symtab.Types$TypeError: cannot find class manifest for element type T
f: [T](p: (Int) => T)(implicit evidence$1: Manifest[T])Array[T]

In addition, following code don't cause error during transforming by ScalaCLPlugin.

scala> def f[T: Manifest](p: Int => T): Array[T] = List(1, 2).map(x => p(x + 1)).toArray
[scalacl] <console>:5 transformed List[Int].map into equivalent while loop.
f: [T](p: (Int) => T)(implicit evidence$1: Manifest[T])Array[T]

<b>What version of the product are you using? On what operating system?</b>

ScalaCL plugin: 0.2.Beta10
-rw-r--r-- 1 1297094 2011-02-03 17:01 scala-2.8.1.final/lib/scalacl-0.2.Beta10-shaded.jar
-rw-r--r-- 1  763351 2011-02-03 17:01 scala-2.8.1.final/misc/scala-devel/plugins/scalacl-compiler-plugin-0.2.Beta10.jar

scala: version 2.8.1.final
java: java version "1.6.0_21" / Java(TM) SE Runtime Environment (build 1.6.0_21-b06)
OS: Linux 2.6.35-25-generic #44-Ubuntu SMP Fri Jan 21 17:40:44 UTC 2011 x86_64 GNU/Linux

Google Code Info:
Issue #: 45
Author: natsumar...@gmail.com
Created On: 2011-02-09T03:44:21.000Z
Closed On:

**Comment by ochafik** [comment]
Assumed stale, please reopen if it's not.
