### ISSUE TITLE
Source build breaks on BridJ

### ISSUE THREAD

**Issue by AODtorusan** [ochafik/nativelibs4java#477]
Hi,

Building the nativelibs4java libraries from the source repository crashes on the BridJ sub-project:

```
> mvn clean install
...
Failed tests: 
  DemanglingTest.testLongLongBackReference:94->demangle:449->checkSymbol:487 Bad type for 1th param : (symbol = null test_add9_long(CLong, CLong, CLong, CLong, CLong, CLong, CLong, CLong, CLong), expecting long and demangled CLong (org.bridj.demangling.Demangler$JavaTypeRef)
   Expected exception: org.bridj.LastError
  STLTest.testList:111 null

Tests in error: 
  NamespacesTest.testSimplyNamespaced:188 ۠UnsatisfiedLink org.bridj.Namespaces...
  NamespacesTest.testFullyNamespaced:200 ۠UnsatisfiedLink org.bridj.NamespacesT...
  NamespacesTest.testTopLevelClass:194 ۠UnsatisfiedLink org.bridj.NamespacesTes...

Tests run: 444, Failures: 3, Errors: 3, Skipped: 4

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] NativeLibs4Java Common Configuration .............. SUCCESS [1.721s]
[INFO] Interop Integration Root .......................... SUCCESS [0.045s]
[INFO] Maven Velocity Code Generator ..................... SUCCESS [11.182s]
[INFO] BridJ (NativeLibs4Java C/C++ Interop Layer) ....... FAILURE [4:07.522s]
[INFO] Anarres JCPP (with JNAerator modifications) ....... SKIPPED
...
[INFO] JarShrinker ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

The error for DemanglingTest:

```
Test set: org.bridj.DemanglingTest
Tests run: 31, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.385 sec <<< FAILURE!
testLongLongBackReference(org.bridj.DemanglingTest)  Time elapsed: 0.196 sec  <<< FAILURE!
java.lang.AssertionError: Bad type for 1th param : (symbol = null test_add9_long(CLong, CLong, CLong, CLong, CLong, CLong, CLong, CLong, CLong), expecting long and demangled CLong (org.bridj.demangling.Demangler$JavaTypeRef)
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.assertTrue(Assert.java:43)
	at org.bridj.DemanglingTest.checkSymbol(DemanglingTest.java:487)
	at org.bridj.DemanglingTest.demangle(DemanglingTest.java:449)
	at org.bridj.DemanglingTest.testLongLongBackReference(DemanglingTest.java:94)
```

The error for STLTest:

```
Test set: org.bridj.STLTest
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.59 sec <<< FAILURE!
testList(org.bridj.STLTest)  Time elapsed: 0.093 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:92)
	at org.junit.Assert.assertTrue(Assert.java:43)
	at org.junit.Assert.assertNull(Assert.java:551)
	at org.junit.Assert.assertNull(Assert.java:562)
	at org.bridj.STLTest.testList(STLTest.java:111)
```

The error for NamespacesTest:

```
Test set: org.bridj.NamespacesTest
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.767 sec <<< FAILURE!
testSimplyNamespaced(org.bridj.NamespacesTest)  Time elapsed: 0.177 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: org.bridj.NamespacesTest$RenamedSimplyNamespacedClass.renamedGetValue()I
	at org.bridj.NamespacesTest$RenamedSimplyNamespacedClass.renamedGetValue(Native Method)
	at org.bridj.NamespacesTest.testSimplyNamespaced(NamespacesTest.java:188)

testFullyNamespaced(org.bridj.NamespacesTest)  Time elapsed: 0.011 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: org.bridj.NamespacesTest$FullyNamespacedClass.renamedGetValue()I
	at org.bridj.NamespacesTest$FullyNamespacedClass.renamedGetValue(Native Method)
	at org.bridj.NamespacesTest.testFullyNamespaced(NamespacesTest.java:200)

testTopLevelClass(org.bridj.NamespacesTest)  Time elapsed: 0.02 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: org.bridj.NamespacesTest$TopLevelClass.renamedGetValue()I
	at org.bridj.NamespacesTest$TopLevelClass.renamedGetValue(Native Method)
	at org.bridj.NamespacesTest.testTopLevelClass(NamespacesTest.java:194)
```

This happens at revision cfee2748 under the following jvm:

```
Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 14:51:28+0100)
Maven home: C:\Program Files (x86)\apache-maven-3.0.5
Java version: 1.7.0_17, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.7.0_17\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 8", version: "6.2", arch: "amd64", family: "windows"
```

I've also updated the full command line output and test logs to http://static.angelcorp.be/stuff/bridj/

**Comment by ochafik** [comment]
This issue was moved to ochafik/BridJ#35
