### ISSUE TITLE
Cannot load scalacl plugin

### ISSUE THREAD

**Issue by mmozum** [ochafik/nativelibs4java#523]
I am trying to run ScalaCL along with scala2.9.3. I put the  scalacl-compiler-plugin-0.3-SNAPSHOT.jar in the $SCALA_HOME/misc/scala-devel/plugins/ folder and try to run the following Test.scala

~/repos/scala-2.9.3/test$ cat Test.scala 
import scalacl._
import scala.math._

object Test {
  def main(args: Array[String]): Unit = {
    val a = (100 until 100000).toArray
    val sum = a.map(_ * 2).zipWithIndex.map(p => p._1 / (p._2 + 1)).sum
    println("sum = " + sum)
  }
}

~/repos/scala-2.9.3/test$ scalac Test.scala 
error: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
...

Caused by: java.lang.NoClassDefFoundError: scala/tools/nsc/MissingRequirementError
	at scalacl.plugin.ScalaCLPlugin.<init>(ScalaCLPlugin.scala:89)
	... 33 more
Caused by: java.lang.ClassNotFoundException: scala.tools.nsc.MissingRequirementError
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
....
...

	... 34 more

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
...
...
...

Caused by: java.lang.NoClassDefFoundError: scala/tools/nsc/MissingRequirementError
	at scalacl.plugin.ScalaCLPlugin.<init>(ScalaCLPlugin.scala:89)
	... 33 more
Caused by: java.lang.ClassNotFoundException: scala.tools.nsc.MissingRequirementError
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)

**Comment by ochafik** [comment]
This issue was moved to ochafik/ScalaCL#20
