### ISSUE TITLE
Parsing arguments: java.lang.IndexOutOfBoundsException: Index: 15, Size: 15

### ISSUE THREAD

**Issue by shevek** [ochafik/nativelibs4java#545]
Error parsing arguments :
```
       -library parted -package org.anarres.device.parted.generated /usr/include/parted/parted.h -mode Directory -runtime JNA -o /home/shevek/java/udev4j/parted/build/generated-sources/jnaerator -f -v(?:erbose)? -Dtime_t=long -D_STDIO_H : java.lang.IndexOutOfBoundsException: Index: 15, Size: 15
```

```
Caused by: java.lang.IndexOutOfBoundsException: Index: 15, Size: 15
        at java.util.ArrayList.rangeCheck(ArrayList.java:635)
        at java.util.ArrayList.get(ArrayList.java:411)
        at com.ochafik.lang.jnaerator.JNAeratorCommandLineArgs$ArgsParser.parse(JNAeratorCommandLineArgs.java:122)
```

0.12-SNAPSHOT

Please consider using JOptSimple, it's very good indeed and appears to be the standard now.

**Comment by ochafik** [comment]
This issue was moved to ochafik/JNAerator#80
