### ISSUE TITLE
[ScalaCL] Test fails

### ISSUE THREAD

**Issue by ochafik** [ochafik/nativelibs4java#65]
<b>What steps will reproduce the problem?</b>
1. install scalacl/0.2.Beta13
2. run the Test object.

<b>What is the expected output? What do you see instead?</b>
Expect that the test will complete.

dave@rudy:~/Programming/Scala_Code/scalacl$ scala Test
Starting...
Symbol '' not found.
Symbol '' not found.
Symbol '__gmon_start__' not found.
Symbol '_Jv_RegisterClasses' not found.
Symbol 'OPENCL_1.0' not found.
Symbol 'OPENCL_1.1' not found.
Symbol '' not found.
Symbol '' not found.
Symbol '__gmon_start__' not found.
Symbol '_Jv_RegisterClasses' not found.
Symbol 'OPENCL_1.0' not found.
Symbol 'OPENCL_1.1' not found.
Got context Cypress
Time[Map2+MapJoin2 in OpenCL] = 270.098299 msecs
Time[Map2+MapJoin2 in OpenCL] = 9.197729 msecs
Time[Map2+MapJoin2 in OpenCL] = 6.854333 msecs
Time[Map2+MapJoin2 in OpenCL] = 7.049002 msecs
Time[Map2+MapJoin2 in OpenCL] = 7.830682 msecs
Time[Map2+MapJoin2 in Scala] = 681.109156 msecs
Time[Map2+MapJoin2 in Scala] = 290.014769 msecs
Time[Map2+MapJoin2 in Scala] = 306.912958 msecs
Time[Map2+MapJoin2 in Scala] = 320.322214 msecs
Time[Map2+MapJoin2 in Scala] = 314.896877 msecs
...
...
aa = WrappedArray(170)
bb = WrappedArray(148)
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:77)
	at Test$.same(Test.scala:47)
	at Test$.main(Test.scala:256)
	at Test.main(Test.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at scala.tools.nsc.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:81)
	at scala.tools.nsc.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:24)
	at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:86)
	at scala.tools.nsc.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:81)
	at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:86)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:83)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)

<b>What version of the product are you using? On what operating system?</b>
scalacl/0.2.Beta13, ati-stream-sdk-v2.3-lnx64, ubuntu 10.10 amd64

<b>For JavaCL / OpenCL4Java / ScalaCL issues, if the HardwareReport runs fine</b>

** Actually it says my system is not configured correctly... although I can compile opencl C code fine... Not sure what the warning messages mean.

Thanks very much!!
-dave

Google Code Info:
Issue #: 63
Author: daveb...@gmail.com
Created On: 2011-04-06T03:37:59.000Z
Closed On:

**Comment by ochafik** [comment]
Closing since stale (ScalaCL was rewritten twice since)
